-- =====================================================================
-- 20260511_security_hardening_rls.sql
-- Pre-launch security hardening for RLS policies.
--
-- Generated by the security audit on 2026-05-11. Apply with:
--   npx supabase db push
-- or paste into the Supabase SQL editor in this exact order.
--
-- The script is idempotent: every block uses IF EXISTS / IF NOT EXISTS.
-- =====================================================================

-- ─────────────────────────────────────────────────────────────────────
-- 1. profiles — block self-promotion to platform_owner / agency_admin
-- ─────────────────────────────────────────────────────────────────────

-- Drop legacy permissive SELECT (PII exposure to anon).
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;

-- Recreate own-profile read.
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile"
    ON public.profiles
    FOR SELECT
    USING (auth.uid() = id);

-- Tighten own-profile UPDATE: cannot change `role` or `email` from the client.
-- (Email changes go through Supabase Auth; role changes only by service role
--  or platform admin via the dedicated policy below.)
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
    ON public.profiles
    FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (
        auth.uid() = id
        AND role = (SELECT role FROM public.profiles WHERE id = auth.uid())
        AND email = (SELECT email FROM public.profiles WHERE id = auth.uid())
    );

-- Platform admins can read any profile.
DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
CREATE POLICY "Admins can view all profiles"
    ON public.profiles
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('platform_owner', 'agency_admin', 'superadmin')
        )
    );

-- Only service role can promote users (admins create users via the
-- invite-user edge function which runs as service role).
DROP POLICY IF EXISTS "Service role manages profile roles" ON public.profiles;
CREATE POLICY "Service role manages profile roles"
    ON public.profiles
    FOR UPDATE
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────
-- 2. organization_members — scoped INSERT/DELETE
-- ─────────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "Org admins can add members" ON public.organization_members;
CREATE POLICY "Org admins can add members"
    ON public.organization_members
    FOR INSERT
    WITH CHECK (
        -- Service role (invite-user) always allowed.
        auth.role() = 'service_role'
        OR
        -- Platform admin always allowed.
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('platform_owner', 'agency_admin', 'superadmin')
        )
        OR
        -- Org owner/admin adding into their own org.
        EXISTS (
            SELECT 1 FROM public.organization_members om
            WHERE om.organization_id = organization_members.organization_id
              AND om.user_id = auth.uid()
              AND om.role IN ('owner', 'admin', 'org_owner')
        )
    );

DROP POLICY IF EXISTS "Org admins can remove members" ON public.organization_members;
CREATE POLICY "Org admins can remove members"
    ON public.organization_members
    FOR DELETE
    USING (
        auth.role() = 'service_role'
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('platform_owner', 'agency_admin', 'superadmin')
        )
        OR EXISTS (
            SELECT 1 FROM public.organization_members om
            WHERE om.organization_id = organization_members.organization_id
              AND om.user_id = auth.uid()
              AND om.role IN ('owner', 'admin', 'org_owner')
        )
    );

-- ─────────────────────────────────────────────────────────────────────
-- 3. organizations — block client-side `is_agency = true` creation
-- ─────────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "Authenticated users can create their own org" ON public.organizations;
CREATE POLICY "Authenticated users can create their own org"
    ON public.organizations
    FOR INSERT
    WITH CHECK (
        auth.uid() IS NOT NULL
        AND COALESCE(is_agency, false) = false
    );

-- ─────────────────────────────────────────────────────────────────────
-- 4. user_subscriptions — only service role writes (webhooks/cron)
-- ─────────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "Platform and Agency admins can manage subscriptions" ON public.user_subscriptions;
DROP POLICY IF EXISTS "Service role manages subscriptions" ON public.user_subscriptions;
CREATE POLICY "Service role manages subscriptions"
    ON public.user_subscriptions
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Users read own subscriptions" ON public.user_subscriptions;
CREATE POLICY "Users read own subscriptions"
    ON public.user_subscriptions
    FOR SELECT
    USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Admins read all subscriptions" ON public.user_subscriptions;
CREATE POLICY "Admins read all subscriptions"
    ON public.user_subscriptions
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('platform_owner', 'agency_admin', 'superadmin')
        )
    );

-- ─────────────────────────────────────────────────────────────────────
-- 5. payment_history — read-only for owner; write only by service role
-- ─────────────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_schema = 'public' AND table_name = 'payment_history') THEN
        EXECUTE 'ALTER TABLE public.payment_history ENABLE ROW LEVEL SECURITY';
    END IF;
END $$;

DROP POLICY IF EXISTS "Service role manages payment history" ON public.payment_history;
CREATE POLICY "Service role manages payment history"
    ON public.payment_history
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Users read own payments" ON public.payment_history;
CREATE POLICY "Users read own payments"
    ON public.payment_history
    FOR SELECT
    USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Admins read all payments" ON public.payment_history;
CREATE POLICY "Admins read all payments"
    ON public.payment_history
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('platform_owner', 'agency_admin', 'superadmin')
        )
    );

-- ─────────────────────────────────────────────────────────────────────
-- 6. whop_webhook_events / ls_webhook_events — service role only
-- ─────────────────────────────────────────────────────────────────────

DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN SELECT unnest(ARRAY['whop_webhook_events', 'ls_webhook_events']) LOOP
        IF EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema = 'public' AND table_name = tbl) THEN
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
            EXECUTE format('DROP POLICY IF EXISTS "Service role only" ON public.%I', tbl);
            EXECUTE format(
                'CREATE POLICY "Service role only" ON public.%I FOR ALL USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')',
                tbl
            );
        END IF;
    END LOOP;
END $$;

-- ─────────────────────────────────────────────────────────────────────
-- 7. subscription_plans — read-only for clients
-- ─────────────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_schema = 'public' AND table_name = 'subscription_plans') THEN
        EXECUTE 'ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY';
    END IF;
END $$;

DROP POLICY IF EXISTS "Anyone can read plans" ON public.subscription_plans;
CREATE POLICY "Anyone can read plans"
    ON public.subscription_plans
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Service role manages plans" ON public.subscription_plans;
CREATE POLICY "Service role manages plans"
    ON public.subscription_plans
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────
-- 8. predictions — kill the "USING (true)" policy
-- ─────────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "Service can manage predictions" ON public.predictions;
DROP POLICY IF EXISTS "Service can insert predictions" ON public.predictions;
DROP POLICY IF EXISTS "Auth users can insert predictions" ON public.predictions;

-- Read-only for clients (the app uses predictions as a public reference).
DROP POLICY IF EXISTS "Anyone can read predictions" ON public.predictions;
CREATE POLICY "Anyone can read predictions"
    ON public.predictions
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Service role manages predictions" ON public.predictions;
CREATE POLICY "Service role manages predictions"
    ON public.predictions
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────
-- 9. v9_debate_runs / v9_agent_outputs — enable RLS, service role writes
-- ─────────────────────────────────────────────────────────────────────

DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN SELECT unnest(ARRAY['v9_debate_runs', 'v9_agent_outputs']) LOOP
        IF EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema = 'public' AND table_name = tbl) THEN
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
            EXECUTE format('DROP POLICY IF EXISTS "Service role writes" ON public.%I', tbl);
            EXECUTE format(
                'CREATE POLICY "Service role writes" ON public.%I FOR ALL USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')',
                tbl
            );
            EXECUTE format('DROP POLICY IF EXISTS "Auth reads" ON public.%I', tbl);
            EXECUTE format(
                'CREATE POLICY "Auth reads" ON public.%I FOR SELECT USING (auth.role() = ''authenticated'')',
                tbl
            );
        END IF;
    END LOOP;
END $$;

-- Lock down the counter function so only service role can call it.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'v9_increment_agent_counter') THEN
        EXECUTE 'ALTER FUNCTION public.v9_increment_agent_counter(UUID, BOOLEAN) SECURITY DEFINER';
        EXECUTE 'REVOKE EXECUTE ON FUNCTION public.v9_increment_agent_counter(UUID, BOOLEAN) FROM PUBLIC, anon, authenticated';
        EXECUTE 'GRANT EXECUTE ON FUNCTION public.v9_increment_agent_counter(UUID, BOOLEAN) TO service_role';
    END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────
-- 10. analysis_jobs_v2 — gate visibility (etl_context contains raw data)
-- ─────────────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_schema = 'public' AND table_name = 'analysis_jobs_v2') THEN
        EXECUTE 'ALTER TABLE public.analysis_jobs_v2 ENABLE ROW LEVEL SECURITY';
    END IF;
END $$;

DROP POLICY IF EXISTS "Service role manages jobs" ON public.analysis_jobs_v2;
CREATE POLICY "Service role manages jobs"
    ON public.analysis_jobs_v2
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Auth users read job status" ON public.analysis_jobs_v2;
CREATE POLICY "Auth users read job status"
    ON public.analysis_jobs_v2
    FOR SELECT
    USING (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────────────────────────────
-- 11. ml_* tables — defensive RLS
-- ─────────────────────────────────────────────────────────────────────

DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN SELECT unnest(ARRAY[
        'ml_training_runs', 'ml_calibration_factors',
        'ml_learned_patterns', 'ml_parlay_calibration'
    ]) LOOP
        IF EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema = 'public' AND table_name = tbl) THEN
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
            EXECUTE format('DROP POLICY IF EXISTS "Service role only" ON public.%I', tbl);
            EXECUTE format(
                'CREATE POLICY "Service role only" ON public.%I FOR ALL USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')',
                tbl
            );
        END IF;
    END LOOP;
END $$;

-- ─────────────────────────────────────────────────────────────────────
-- 12. Sanity: re-affirm RLS enabled on critical tables
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.profiles                ENABLE ROW LEVEL SECURITY;
DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN SELECT unnest(ARRAY[
        'organizations', 'organization_members',
        'user_subscriptions', 'payment_history',
        'predictions', 'analisis', 'reports_v2', 'value_picks_v2',
        'parlays', 'parlay_combos_v2'
    ]) LOOP
        IF EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema = 'public' AND table_name = tbl) THEN
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        END IF;
    END LOOP;
END $$;

-- =====================================================================
-- VERIFICATION QUERIES (run manually after applying):
--
-- -- Should return 0: anyone able to UPDATE another user's role
-- SELECT polname, polqual, polwithcheck
-- FROM pg_policy
-- WHERE polrelid = 'public.profiles'::regclass
--   AND polcmd = 'w';
--
-- -- All payment-related tables should have RLS enabled
-- SELECT relname, relrowsecurity
-- FROM pg_class
-- WHERE relname IN ('user_subscriptions','payment_history','whop_webhook_events');
-- =====================================================================
